# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ub12_java"
  config.vm.box_url = "https://www.dropbox.com/s/qcbfbfw8s24nxys/ub12_java.box?dl=1"

  config.vm.provider 'virtualbox' do |v|  
    v.customize ["modifyvm", :id, "--memory", 1000]
    v.customize ["modifyvm", :id, "--cpus", 2]
  end

  # Our basic setup script, along the Vagrant Docs Getting Started guide
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provision :puppet, :options => ["--fileserverconfig=/vagrant/fileserver.conf"] do |puppet|
    puppet.manifests_path = "./puppet/manifests"
    puppet.manifest_file  = "default.pp"
    puppet.hiera_config_path = "./puppet/hiera.yaml"
    puppet.module_path = "./puppet/modules"
#    puppet.options = "--verbose --debug"
  end

  # Some jobs scripted here, as I don't know puppet well enough
  # config.vm.provision :shell, path: "postVagrantUp.sh"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.50.4"

  # Version with port mapping
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  #config.vm.network "forwarded_port", guest: 9200, host: 9200

end
